// packages/docs/src/lib/showcases/bar-chart/highchart/Chart.svelte
<script lang="ts">
	import Widget from '@meursyphus/flitter-svelte';
	import { BarChart, type BarChartCustom } from '@meursyphus/headless-chart';
	import {
		Text,
		Border,
		BoxDecoration,
		Column,
		Container,
		EdgeInsets,
		Row,
		SizedBox,
		TextStyle,
		Padding,
		MainAxisSize,
		MainAxisAlignment,
		Flexible,
		Stack,
		Positioned,
		CrossAxisAlignment,
		BorderRadius,
		Radius,
		Alignment,
		FractionalTranslation,
		BoxShadow
	} from '@meursyphus/flitter';
	const data = {
		labels: ['Africa', 'America', 'Asia', 'Europe'],
		datasets: [
			{
				legend: 'Year 1990',
				values: [631, 727, 3292, 721]
			},
			{
				legend: 'Year 2000',
				values: [814, 841, 3714, 726]
			},
			{
				legend: 'Year 2018',
				values: [1276, 1007, 4561, 746]
			}
		]
	};
	const backgroundColors = ['rgb(44,175,254)', 'rgb(84,79,197)', 'rgb(0,226,114)'];

	function Layout(...[{ legends, plot, title }]: Parameters<BarChartCustom['layout']>) {
		return Container({
			padding: EdgeInsets.only({ left: 60, bottom: 70, right: 60 }),
			child: Stack({
				children: [
					Positioned({
						top: 20,
						right: 0,
						child: Text('highchart 따라하기 :)', {
							style: new TextStyle({
								fontSize: 14,
								color: '#999999',
								fontFamily: 'Noto Sans JP'
							})
						})
					}),
					Positioned({
						top: 0,
						left: -60,
						child: Column({
							crossAxisAlignment: CrossAxisAlignment.start,
							mainAxisSize: MainAxisSize.min,
							children: [
								Text('Historic World Population by Region', {
									style: new TextStyle({
										fontSize: 20,
										fontWeight: 'bold',
										fontFamily: 'Noto Sans JP'
									})
								}),
								Text('Source: Wikipedia.org', {
									style: new TextStyle({
										fontSize: 14,
										fontWeight: '600',
										color: '#666666',
										fontFamily: 'Noto Sans JP'
									})
								})
							]
						})
					}),
					Padding({
						padding: EdgeInsets.only({ top: 60 }),
						child: plot
					}),
					Positioned({
						top: 90,
						right: 40,
						child: Container({
							padding: EdgeInsets.symmetric({ horizontal: 10, vertical: 8 }),
							decoration: new BoxDecoration({
								color: 'white',
								boxShadow: [
									new BoxShadow({
										color: 'black',
										offset: { x: 0, y: 0 },
										blurRadius: 2
									})
								]
							}),
							child: Column({
								mainAxisSize: MainAxisSize.min,
								children: legends
							})
						})
					})
				]
			})
		});
	}
	function XAxisLabel(...[{ name }]: Parameters<BarChartCustom['xAxisLabel']>) {
		return Padding({
			padding: EdgeInsets.only({ top: 10 }),
			child: Text(name, {
				style: new TextStyle({
					fontFamily: 'Noto Sans JP',
					fontWeight: '600',
					fontSize: 14,
					color: '#333333'
				})
			})
		});
	}
	function YAxisLabel(...[{ name }]: Parameters<BarChartCustom['yAxisLabel']>) {
		return Padding({
			padding: EdgeInsets.only({ right: 10 }),
			child: Text(name, {
				style: new TextStyle({
					fontFamily: 'Noto Sans JP',
					fontWeight: '600',
					fontSize: 14,
					color: '#333333'
				})
			})
		});
	}
	function XAxisTick(...[,]: Parameters<BarChartCustom['xAxisTick']>) {
		return Container({
			height: 6,
			width: 1,
			color: '#DDDDDD'
		});
	}
	function YAxisTick(...[,]: Parameters<BarChartCustom['yAxisTick']>) {
		return Container({
			height: 1,
			width: 6,
			color: '#DDDDDD'
		});
	}
	function YAxisLine(...[,]: Parameters<BarChartCustom['yAxisLine']>) {
		return Container({
			color: '#BBBBBB',
			width: 1,
			height: Infinity
		});
	}
	function xAxisLine(...[,]: Parameters<BarChartCustom['xAxisLine']>) {
		return Container({
			color: '#BBBBBB',
			height: 1,
			width: Infinity
		});
	}
	function Series(
		...[
			{ barGroups },
			{
				data: { labels }
			}
		]: Parameters<BarChartCustom['series']>
	) {
		const count = labels.length;
		return Stack({
			children: [
				Column({
					mainAxisAlignment: MainAxisAlignment.spaceBetween,
					children: [
						...Array.from({ length: count + 1 }, (_, index) =>
							Container({
								height: 1,
								color: index !== count ? '#DDDDDD' : 'transparent'
							})
						)
					]
				}),
				Column({
					children: barGroups.map((barGroup) => Flexible({ flex: 1, child: barGroup }))
				})
			]
		});
	}
	function Legend(...[{ name, index }]: Parameters<BarChartCustom['legend']>) {
		return Padding({
			padding: EdgeInsets.symmetric({ vertical: 2 }),
			child: Row({
				mainAxisAlignment: MainAxisAlignment.center,
				mainAxisSize: MainAxisSize.min,
				children: [
					Container({
						width: 12,
						height: 12,
						decoration: new BoxDecoration({
							shape: 'circle',
							color: backgroundColors[index]
						})
					}),
					SizedBox({ width: 8 }),
					Text(name, {
						style: new TextStyle({
							fontFamily: 'monospace',
							fontSize: 12,
							fontWeight: '500',
							color: '#111111'
						})
					})
				]
			})
		});
	}
	function Bar(...[{ label, legend, value }, { data }]: Parameters<BarChartCustom['bar']>) {
		const index = data.datasets.findIndex((d) => d.legend === legend);
		const backgroundColor = backgroundColors[index];
		return Container({
			width: Infinity,
			height: 14,
			alignment: Alignment.centerRight,
			decoration: new BoxDecoration({
				color: backgroundColor,
				borderRadius: BorderRadius.only({
					topRight: Radius.circular(7),
					bottomRight: Radius.circular(7)
				})
			}),
			child: FractionalTranslation({
				translation: { x: 1, y: 0 },
				child: Padding({
					padding: EdgeInsets.only({ left: 6 }),
					child: Text(value.toLocaleString('ko-KR').replace(',', ' '), {
						style: new TextStyle({
							fontFamily: 'Noto Sans JP',
							fontSize: 12,
							fontWeight: 'bold'
						})
					})
				})
			})
		});
	}
</script>

<Widget
	height="400px"
	widget={BarChart({
		data,
		direction: 'horizontal',
		custom: {
			layout: Layout,
			xAxisLabel: XAxisLabel,
			yAxisLabel: YAxisLabel,
			xAxisLine: xAxisLine,
			yAxisTick: () => SizedBox.shrink(),
			xAxisTick: () => SizedBox.shrink(),
			legend: Legend,
			series: Series,
			yAxisLine: () => SizedBox.shrink(),
			bar: Bar
		}
	})}
/>

// packages/docs/playground/chart.tsx
import Widget from "@meursyphus/flitter-react";
import { BarChart } from "@meursyphus/headless-chart";
import {
  Text,
  Border,
  BorderSide,
  BoxDecoration,
  Column,
  Container,
  EdgeInsets,
  Row,
  SizedBox,
  TextStyle,
  Padding,
  MainAxisSize,
  MainAxisAlignment,
  Stack,
  Positioned
} from "@meursyphus/flitter";

const data = {
  labels: ["January", "February", "March", "April", "May", "June", "July"],
  datasets: [
    {
      legend: "My First Dataset",
      values: [65, 59, 80, 81, 56, 55, 40],
    },
  ],
};

const backgroundColors = [
  "rgba(255, 99, 132, 0.2)",
  "rgba(255, 159, 64, 0.2)",
  "rgba(255, 205, 86, 0.2)",
  "rgba(75, 192, 192, 0.2)",
  "rgba(54, 162, 235, 0.2)",
  "rgba(153, 102, 255, 0.2)",
  "rgba(201, 203, 207, 0.2)",
];
const borderColors = [
  "rgb(255, 99, 132)",
  "rgb(255, 159, 64)",
  "rgb(255, 205, 86)",
  "rgb(75, 192, 192)",
  "rgb(54, 162, 235)",
  "rgb(153, 102, 255)",
  "rgb(201, 203, 207)",
];

const chart = BarChart({
  data,
  custom: {
    layout: (...[{ legends, plot }]) => 
      Container({
        padding: EdgeInsets.only({ left: 30, bottom: 70 }),
        child: Stack({
          children: [
            Positioned({
              top: 0,
              right: 0,
              child: Text("Inspired by Chart.js", {
                style: new TextStyle({
                  fontSize: 14,
                  color: "#999999",
                  fontFamily: "Noto Sans JP",
                }),
              }),
            }),
            Column({
              children: [
                Row({
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [...legends, SizedBox({ width: 30 })],
                }),
                SizedBox({ height: 5 }),
                plot,
              ],
            }),
          ],
        }),
      }),
    bar: (...[{ label }]) => {
      const index = data.labels.indexOf(label);
      const backgroundColor = backgroundColors[index];
      const borderSide = new BorderSide({
        color: borderColors[index],
        width: 1,
      });
      return Container({
        width: Infinity,
        margin: EdgeInsets.symmetric({ horizontal: 8 }),
        height: Infinity,
        decoration: new BoxDecoration({
          color: backgroundColor,
          border: new Border({
            left: borderSide,
            right: borderSide,
            top: borderSide,
          }),
        }),
      });
    },
    xAxisLabel: (...[{ name }]) => Padding({
      padding: EdgeInsets.only({ top: 1 }),
      child: Text(name, {
        style: new TextStyle({
          fontFamily: "Noto Sans JP",
          fontSize: 12,
          color: "#666666",
        }),
      }),
    }),
    yAxisLabel: (...[{ name }]) => Padding({
      padding: EdgeInsets.only({ right: 1 }),
      child: Text(name, {
        style: new TextStyle({
          fontFamily: "Noto Sans JP",
          fontSize: 12,
          color: "#666666",
        }),
      }),
    }),
    xAxisTick: () => Container({
      height: 6,
      width: 1,
      color: "#DDDDDD",
    }),
    yAxisTick: () => Container({
      height: 1,
      width: 6,
      color: "#DDDDDD",
    }),
    yAxisLine: () => Container({
      color: "#BBBBBB",
      width: 1,
      height: Infinity,
    }),
    xAxisLine: () => Container({
      color: "#BBBBBB",
      height: 1,
      width: Infinity,
    }),
    legend: (...[{ name }]) => Row({
      mainAxisAlignment: MainAxisAlignment.center,
      mainAxisSize: MainAxisSize.min,
      children: [
        Container({
          width: 36,
          height: 12,
          decoration: new BoxDecoration({
            color: "rgba(255, 99, 132, 0.2)",
            border: Border.all({ color: "rgb(255, 99, 132)" }),
          }),
        }),
        SizedBox({ width: 5 }),
        Text(name, {
          style: new TextStyle({
            fontFamily: "Noto Sans JP",
            fontSize: 14,
            color: "#666666",
          }),
        }),
      ],
    }),
    gridXLine: () => Container({ height: 1, color: "#EEEEEE" }),
    gridYLine: () => Container({ width: 1, color: "#EEEEEE" }),
  },
});

export default function App() {
  return (
    <Widget
      width="auto"
      height="400px"
      widget={chart}
      renderer="svg"
    />
  );
}
